# Generated by Django 4.2.6 on 2023-10-30 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iranian_cities.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iranian_cities', '0004_remove_abadi_shhahr'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('otp', models.SlugField(blank=True, null=True)),
                ('otp_created', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('mobile', models.PositiveIntegerField()),
                ('mobile_2', models.PositiveIntegerField()),
                ('code_post', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('post_method', models.CharField(choices=[('noramal', 'عادی'), ('fast', 'پیشتاز')], max_length=15)),
                ('is_ok', models.BooleanField(default=False)),
                ('city', iranian_cities.fields.ShahrField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.shahr')),
                ('state', iranian_cities.fields.OstanField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.ostan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
